// Autogenerated by BaseScript v0.1.44

// Your code below this line

var __dirname = "\\storage\\emulated\\0\\base\\basescript\\test", __filename = "\\storage\\emulated\\0\\base\\basescript\\test\\interface.bs";

BS.customTypes["Person"] = function Person(value) {if (!BS.types.Object(value)) return false;if (Object.keys(value).length !== 1) return false;if (!BS.validateType(value["name"], BS.ifTypeExists(["String"]), false)) {return false;}return true;};function Tim() {const args=Array.from(arguments);return BS.expectValue(({name:"Tim",}),["Person"]);throw new TypeError("Invalid return type at line 5, col 1");};console.log(Tim());
