(function(l,k){"object"===typeof module&&module.exports?module.exports=k():l.nearley=k()})(this,function(){function l(a,b,c){this.id=++l.highestId;this.name=a;this.symbols=b;this.postprocess=c;return this}function k(a,b,c,e){this.rule=a;this.dot=b;this.reference=c;this.data=[];this.wantedBy=e;this.isComplete=this.dot===a.symbols.length}function m(a,b){this.grammar=a;this.index=b;this.states=[];this.wants={};this.scannable=[];this.completed={}}function q(a,b){this.rules=a;this.start=b||this.rules[0].name;
var c=this.byName={};this.rules.forEach(function(e){c.hasOwnProperty(e.name)||(c[e.name]=[]);c[e.name].push(e)})}function n(){this.reset("")}function h(a,b,c){a instanceof q?c=b:a=q.fromCompiled(a,b);this.grammar=a;this.options={keepHistory:!1,lexer:a.lexer||new n};for(var e in c||{})this.options[e]=c[e];this.lexer=this.options.lexer;this.lexerState=void 0;b=new m(a,0);this.table=[b];b.wants[a.start]=[];b.predict(a.start);b.process();this.current=0}function A(a){var b=typeof a;if("string"===b)return a;
if("object"===b){if(a.literal)return JSON.stringify(a.literal);if(a instanceof RegExp)return"character matching "+a;if(a.type)return a.type+" token";if(a.test)return"token matching "+String(a.test);throw Error("Unknown symbol type: "+a);}}function w(a){var b=typeof a;if("string"===b)return a;if("object"===b){if(a.literal)return JSON.stringify(a.literal);if(a instanceof RegExp)return a.toString();if(a.type)return"%"+a.type;if(a.test)return"<"+String(a.test)+">";throw Error("Unknown symbol type: "+
a);}}l.highestId=0;l.prototype.toString=function(a){a="undefined"===typeof a?this.symbols.map(w).join(" "):this.symbols.slice(0,a).map(w).join(" ")+" \u25cf "+this.symbols.slice(a).map(w).join(" ");return this.name+" \u2192 "+a};k.prototype.toString=function(){return"{"+this.rule.toString(this.dot)+"}, from: "+(this.reference||0)};k.prototype.nextState=function(a){var b=new k(this.rule,this.dot+1,this.reference,this.wantedBy);b.left=this;b.right=a;b.isComplete&&(b.data=b.build(),b.right=void 0);return b};
k.prototype.build=function(){var a=[],b=this;do a.push(b.right.data),b=b.left;while(b.left);a.reverse();return a};k.prototype.finish=function(){this.rule.postprocess&&(this.data=this.rule.postprocess(this.data,this.reference,h.fail))};m.prototype.process=function(a){a=this.states;for(var b=this.wants,c=this.completed,e=0;e<a.length;e++){var d=a[e];if(d.isComplete){if(d.finish(),d.data!==h.fail){for(var g=d.wantedBy,f=g.length;f--;)this.complete(g[f],d);d.reference===this.index&&(f=d.rule.name,(this.completed[f]=
this.completed[f]||[]).push(d))}}else if(f=d.rule.symbols[d.dot],"string"!==typeof f)this.scannable.push(d);else if(b[f]){if(b[f].push(d),c.hasOwnProperty(f))for(g=c[f],f=0;f<g.length;f++)this.complete(d,g[f])}else b[f]=[d],this.predict(f)}};m.prototype.predict=function(a){for(var b=this.grammar.byName[a]||[],c=0;c<b.length;c++){var e=new k(b[c],0,this.index,this.wants[a]);this.states.push(e)}};m.prototype.complete=function(a,b){a=a.nextState(b);this.states.push(a)};q.fromCompiled=function(a,b){var c=
a.Lexer;a.ParserStart&&(b=a.ParserStart,a=a.ParserRules);a=a.map(function(e){return new l(e.name,e.symbols,e.postprocess)});a=new q(a,b);a.lexer=c;return a};n.prototype.reset=function(a,b){this.buffer=a;this.index=0;this.line=b?b.line:1;this.lastLineBreak=b?-b.col:0};n.prototype.next=function(){if(this.index<this.buffer.length){var a=this.buffer[this.index++];"\n"===a&&(this.line+=1,this.lastLineBreak=this.index);return{value:a}}};n.prototype.save=function(){return{line:this.line,col:this.index-this.lastLineBreak}};
n.prototype.formatError=function(a,b){function c(f,p){f=String(f);return Array(p-f.length+1).join(" ")+f}a=this.buffer;if("string"===typeof a){var e=a.split("\n").slice(Math.max(0,this.line-5),this.line),d=a.indexOf("\n",this.index);-1===d&&(d=a.length);a=this.index-this.lastLineBreak;var g=String(this.line).length;b+=" at line "+this.line+" col "+a+":\n\n";b+=e.map(function(f,p){return c(this.line-e.length+p+1,g)+" "+f},this).join("\n");return b+="\n"+c("",g+a)+"^\n"}return b+" at index "+(this.index-
1)};h.fail={};h.prototype.feed=function(a){var b=this.lexer;b.reset(a,this.lexerState);for(var c;;){try{if(c=b.next(),!c)break}catch(r){throw a=new m(this.grammar,this.current+1),this.table.push(a),b=Error(this.reportLexerError(r)),b.offset=this.current,b.token=r.token,b;}var e=this.table[this.current];this.options.keepHistory||delete this.table[this.current-1];var d=this.current+1;a=new m(this.grammar,d);this.table.push(a);for(var g=void 0!==c.text?c.text:c.value,f=b.constructor===n?c.value:c,p=
e.scannable,y=p.length;y--;){var t=p[y],u=t.rule.symbols[t.dot];if(u.test?u.test(f):u.type?u.type===c.type:u.literal===g)t=t.nextState({data:f,token:c,isToken:!0,reference:d-1}),a.states.push(t)}a.process();if(0===a.states.length){b=Error(this.reportError(c));b.offset=this.current;b.token=c;c=b.message.split("\nA ").map(v=>v.split(" based on:")[0]);let r=!1,z=!1;b=[...(new Set(c.slice(1)))].filter(v=>"==;===;!=;!==;>;<;>=;<=;is;is not".split(";").map(x=>`"${x}"`).includes(v)?(r=!0,!1):"* ** + - / %".split(" ").map(x=>
`"${x}"`).includes(v)?(z=!0,!1):!0).join(", ");c=[c[0],b,r?", comparision operator":"",z?", math operator":""].join("");throw c;throw b;}this.options.keepHistory&&(e.lexerState=b.save());this.current++}e&&(this.lexerState=b.save());this.results=this.finish();return this};h.prototype.reportLexerError=function(a){var b=a.token;if(b){var c="input "+JSON.stringify(b.text[0])+" (lexer error)";a=this.lexer.formatError(b,"Syntax error")}else c="input (lexer error)",a=a.message;return this.reportErrorCommon(a,
c)};h.prototype.reportError=function(a){var b=(a.type?a.type+" token: ":"")+JSON.stringify(void 0!==a.value?a.value:a);a=this.lexer.formatError(a,"Syntax error");return this.reportErrorCommon(a,b)};h.prototype.reportErrorCommon=function(a,b){var c=[];c.push(a);a=this.table[this.table.length-2];var e=a.states.filter(function(d){return(d=d.rule.symbols[d.dot])&&"string"!==typeof d});0===e.length?(c.push("Unexpected "+b+". I did not expect any more input. Here is the state of my parse table:\n"),this.displayStateStack(a.states,
c)):(c.push("Unexpected "+b+". Instead, I was expecting to see one of the following:\n"),e.map(function(d){return this.buildFirstStateStack(d,[])||[d]},this).forEach(function(d){var g=d[0];g=this.getSymbolDisplay(g.rule.symbols[g.dot]);c.push("A "+g+" based on:");this.displayStateStack(d,c)},this));c.push("");return c.join("\n")};h.prototype.displayStateStack=function(a,b){for(var c,e=0,d=0;d<a.length;d++){var g=a[d];g=g.rule.toString(g.dot);g===c?e++:(0<e&&b.push("    ^ "+e+" more lines identical to this"),
e=0,b.push("    "+g));c=g}};h.prototype.getSymbolDisplay=function(a){return A(a)};h.prototype.buildFirstStateStack=function(a,b){if(-1!==b.indexOf(a))return null;if(0===a.wantedBy.length)return[a];var c=a.wantedBy[0];b=[a].concat(b);c=this.buildFirstStateStack(c,b);return null===c?null:[a].concat(c)};h.prototype.save=function(){var a=this.table[this.current];a.lexerState=this.lexerState;return a};h.prototype.restore=function(a){var b=a.index;this.current=b;this.table[b]=a;this.table.splice(b+1);this.lexerState=
a.lexerState;this.results=this.finish()};h.prototype.rewind=function(a){if(!this.options.keepHistory)throw Error("set option `keepHistory` to enable rewinding");this.restore(this.table[a])};h.prototype.finish=function(){var a=[],b=this.grammar.start;this.table[this.table.length-1].states.forEach(function(c){c.rule.name===b&&c.dot===c.rule.symbols.length&&0===c.reference&&c.data!==h.fail&&a.push(c)});return a.map(function(c){return c.data})};return{Parser:h,Grammar:q,Rule:l}});
